spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GAy9BspyF6sKGTVMT5K
      secret-key: DgT9eDqnM96QrQfsTSiU7DTn4Sd5wD
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hello7
  application:
    name: gulimall-third-party

server:
  port: 30000

